version: 0.2

phases:
  build:
    commands:
    #  - cd ChuckSwapCAssessment
      - dotnet restore
      - dotnet test
      - dotnet publish -c release -o ./build_output ChuckSwapCAssessment/ChuckSwapiCAssessment.API.csproj -r linux-x64 --self-contained true

artifacts:
  files:
    - build_output/**/*
    ##- .\ChuckSwapCAssessment\bin\Release\netcoreapp3.1\*
    ##- AspNetCoreWebService/build_output/**/*
    - scripts/**/*
    ##- .\scripts\start_server.ps1
    ##- .\scripts\stop_server.ps1
    - appspec.yml
  ##base-directory: ./src/output